[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.31"

[features]
seeds = false
skip-lint = false

[programs.localnet]
oft = "71Lm7pDFRYgag4RRRgHvEpSxGCDhSEZCNGT2LU89WqhN"

[programs.devnet]
oft = "71Lm7pDFRYgag4RRRgHvEpSxGCDhSEZCNGT2LU89WqhN"

[programs.mainnet]
oft = "71Lm7pDFRYgag4RRRgHvEpSxGCDhSEZCNGT2LU89WqhN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
